"""
Generates a clinician-readable PDF report: annotated X-ray + findings table
+ severity summary. This is the artifact that makes the project feel like a
product rather than a model demo.
"""
import io
from datetime import datetime

import cv2
import numpy as np
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage,
)

SEVERITY_COLOR = {
    "mild": colors.HexColor("#2e7d32"),
    "moderate": colors.HexColor("#ef6c00"),
    "severe": colors.HexColor("#c62828"),
}


def annotate_image(image_bgr: np.ndarray, findings) -> np.ndarray:
    annotated = image_bgr.copy()
    color_map = {"mild": (46, 125, 50), "moderate": (0, 108, 239), "severe": (40, 40, 198)}
    for f in findings:
        x1, y1, x2, y2 = [int(v) for v in f.tooth_box]
        color = color_map.get(f.severity, (255, 255, 255))
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 2)
        label = f"{f.finding_class} ({f.severity})"
        cv2.putText(annotated, label, (x1, max(y1 - 6, 10)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)
    return annotated


def generate_pdf_report(image_bgr: np.ndarray, findings, patient_name: str = "N/A") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Dental AI Diagnostic Report", styles["Title"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    story.append(Paragraph(f"Patient: {patient_name}", styles["Normal"]))
    story.append(Spacer(1, 8 * mm))

    annotated = annotate_image(image_bgr, findings)
    ok, buf_img = cv2.imencode(".png", annotated)
    img_stream = io.BytesIO(buf_img.tobytes())
    story.append(RLImage(img_stream, width=160 * mm, height=160 * mm * annotated.shape[0] / annotated.shape[1]))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(f"Findings summary ({len(findings)} detected)", styles["Heading2"]))

    table_data = [["Finding", "Confidence", "Lesion Area %", "Severity"]]
    for f in findings:
        table_data.append([
            f.finding_class,
            f"{f.detector_confidence:.2f}",
            f"{f.lesion_area_ratio * 100:.1f}%",
            f.severity.upper(),
        ])

    table = Table(table_data, colWidths=[55 * mm, 30 * mm, 35 * mm, 30 * mm])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1565c0")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]
    for i, f in enumerate(findings, start=1):
        style_cmds.append(("TEXTCOLOR", (3, i), (3, i), SEVERITY_COLOR.get(f.severity, colors.black)))
    table.setStyle(TableStyle(style_cmds))
    story.append(table)

    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Disclaimer: This report is generated by an AI-assisted diagnostic system and is intended "
        "to support, not replace, evaluation by a licensed dental professional.",
        styles["Italic"],
    ))

    doc.build(story)
    return buf.getvalue()
